<?php

namespace App\Widgets\Form;

use App\Helpers\Helper;
use App\Models\Category;

/**
 *  |--------------------------------------------------------------------------
 *  | public $controller = App/classPath/MyWidget::class; (optional)
 *  | public $presenter = App/classPath/WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $contextAs = '$data'; (Default is : '$data')
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  | public $cacheTags = []; (optional) (Not available for 'file system' cache driver)
 *  |--------------------------------------------------------------------------
 */
class CategorySelector
{
    public $cacheLifeTime = 0;

    public $template = 'Widgets::Form.CategorySelectorView';

    public function data($item, $type = null)
    {
        $required = Helper::checkIfRequired($item, 'company_id');

        $query = Category::orderBy('name', 'asc')
            ->whereNull('deleted_at')
            ->orderBy('name', 'asc');

        if (!empty($type)) {
            $query = $query->where('category_type', '=', $type);
        }
        $categoryList = array('' => trans('general.select_category')) + $query->pluck('name', 'id')->toArray();

        return ['value' => \Input::old('category_id', $item->category_id), 'category_list' => $categoryList, 'required' => $required];
    }


    /**
     * By default the cacheKey of your widget output does not
     * depend on any Global variables like $_GET. So if the final
     * widget output depend on them you should return them here.
     * otherwise you get undesired results out of the cache store.
     */
    public function extraCacheKeyDependency()
    {
        return [];
    }

}
