version: 1

environment:
  php: 8.0
  node: 12

services:
  - mysql: 5.7

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches: .*

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.testing.example .env
      cp -v .env.testing.example .env.testing
      composer install --no-interaction --prefer-dist --optimize-autoloader

  - name: Generate Key
    cmd: |
      php artisan key:generate --force

  - name: Passport Keys
    cmd: |
      php artisan passport:keys

  - name: Run Migrations
    cmd: |
      php artisan migrate --force

  - name: PHPUnit Unit Tests
    cmd: |
      php artisan test --testsuite Unit

  - name: PHPUnit Feature Tests
    cmd: |
      php artisan test --testsuite Feature
