<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLabelTemplatesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('label_templates', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('page_format')->nullable();
            $table->string('page_orientation')->nullable();
            $table->decimal('column1_x',6)->nullable();
            $table->decimal('column2_x', 6)->nullable();
            $table->decimal('row1_y', 6)->nullable();
            $table->decimal('row2_y', 6)->nullable();
            $table->decimal('label_width', 6)->nullable();
            $table->decimal('label_height', 6)->nullable();
            $table->decimal('barcode_size', 6)->nullable();
            $table->decimal('barcode_margin', 6)->nullable();
            $table->decimal('title_size', 6)->nullable();
            $table->decimal('title_margin', 6)->nullable();
            $table->decimal('field_size', 6)->nullable();
            $table->decimal('field_margin', 6)->nullable();
            $table->decimal('label_size', 6)->nullable();
            $table->decimal('label_margin', 6)->nullable();
            $table->decimal('tag_size', 6)->nullable();
            $table->decimal('logo_max_width', 6)->nullable();
            $table->decimal('logo_margin', 6)->nullable();
            $table->decimal('measurement_unit', 6)->nullable();
            $table->decimal('margin_top', 6)->nullable();
            $table->decimal('margin_bottom', 6)->nullable();
            $table->decimal('margin_left', 6)->nullable();
            $table->decimal('margin_right', 6)->nullable();
            $table->integer('fields_supported')->default(1);
            $table->boolean('tag_option')->nullable();
            $table->boolean('1d_barcode_option')->nullable();
            $table->boolean('2d_barcode_option')->nullable();
            $table->boolean('logo_option')->nullable();
            $table->boolean('title_option')->nullable();
            $table->decimal('tape_height', 6)->nullable();
            $table->decimal('tape_width', 6)->nullable();
            $table->decimal('tape_margin_sides', 6)->nullable();
            $table->decimal('tape_margin_ends', 6)->nullable();
            $table->decimal('tape_text_size_mod', 6)->nullable();
            $table->timestamps();
        });
        $defaults =
            [
                [
                    "name" => "Avery 5267",
                    "page_format" => "LETTER",
                    "page_orientation" => "P",
                    "column1_x" => 21.60,
                    "column2_x" => 169.20,
                    "row1_y" => 36.10,
                    "row2_y" => 72.10,
                    "label_width" => 126.00,
                    "label_height" => 36.00,
                    "barcode_size" => 0.18,
                    "barcode_margin" => 0.00,
                    "title_size" => 0.14,
                    "title_margin" => null,
                    "field_size" => 0.15,
                    "field_margin" => null,
                    "label_size" => null,
                    "label_margin" => null,
                    "tag_size" => null,
                    "logo_max_width" => null,
                    "logo_margin" => null,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.02,
                    "margin_bottom" => 0.00,
                    "margin_left" => 0.04,
                    "margin_right" => 0.04,
                    "fields_supported" => 1,
                    "tag_option" => 0,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 0,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 0.57,
                    "tape_width" => null,
                    "tape_margin_sides" => 0.20,
                    "tape_margin_ends" => 0.16,
                    "tape_text_size_mod" => 0.24
                ],
                [
                    "name" => "Avery 5520",
                    "page_format" => "LETTER",
                    "page_orientation" => "P",
                    "column1_x" => 13.55,
                    "column2_x" => 211.55,
                    "row1_y" => 36.10,
                    "row2_y" => 108.10,
                    "label_width" => 189.35,
                    "label_height" => 72.00,
                    "barcode_size" => null,
                    "barcode_margin" => 0.08,
                    "title_size" => 0.14,
                    "title_margin" => 0.04,
                    "field_size" => 0.15,
                    "field_margin" => null,
                    "label_size" => 0.09,
                    "label_margin" => -0.02,
                    "tag_size" => null,
                    "logo_max_width" => null,
                    "logo_margin" => null,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.06,
                    "margin_bottom" => 0.06,
                    "margin_left" => 0.06,
                    "margin_right" => 0.06,
                    "fields_supported" => 3,
                    "tag_option" => 0,
                    "1d_barcode_option" => 0,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 0.21,
                    "tape_width" => null,
                    "tape_margin_sides" => 0.20,
                    "tape_margin_ends" => 0.25,
                    "tape_text_size_mod" => 0.35,
                ],
                [
                    "name" => "Avery L7162 1D Barcode",
                    "page_format" => "A4",
                    "page_orientation" => "P",
                    "column1_x" => 13.25,
                    "column2_x" => 301.25,
                    "row1_y" => 43.05,
                    "row2_y" => 151.05,
                    "label_width" => 280.80,
                    "label_height" => 108.00,
                    "barcode_size" => null,
                    "barcode_margin" => 1.80,
                    "title_size" => 5.00,
                    "title_margin" => 1.80,
                    "field_size" => 4.80,
                    "field_margin" => 0.30,
                    "label_size" => 2.35,
                    "label_margin" => -0.30,
                    "tag_size" => 4.80,
                    "logo_max_width" => null,
                    "logo_margin" => null,
                    "measurement_unit" => 0.00,
                    "margin_top" => 1.00,
                    "margin_bottom" => 1.00,
                    "margin_left" => 1.00,
                    "margin_right" => 1.00,
                    "fields_supported" => 4,
                    "tag_option" => 1,
                    "1d_barcode_option" => 0,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 0.37,
                    "tape_width" => null,
                    "tape_margin_sides" => 0.54,
                    "tape_margin_ends" => 0.66,
                    "tape_text_size_mod" => 0.47,
                ],
                [
                    "name" => "Avery L7162 2D Barcode",
                    "page_format" => "A4",
                    "page_orientation" => "P",
                    "column1_x" => 13.25,
                    "column2_x" => 301.25,
                    "row1_y" => 37.00,
                    "row2_y" => 133.00,
                    "label_width" => 280.80,
                    "label_height" => 96.00,
                    "barcode_size" => null,
                    "barcode_margin" => 1.60,
                    "title_size" => 4.20,
                    "title_margin" => 1.40,
                    "field_size" => 4.60,
                    "field_margin" => 0.30,
                    "label_size" => 2.20,
                    "label_margin" => -0.50,
                    "tag_size" => 4.60,
                    "logo_max_width" => null,
                    "logo_margin" => null,
                    "measurement_unit" => 0.00,
                    "margin_top" => 1.00,
                    "margin_bottom" => 1.00,
                    "margin_left" => 1.00,
                    "margin_right" => 1.00,
                    "fields_supported" => 4,
                    "tag_option" => 1,
                    "1d_barcode_option" => 0,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 0.97,
                    "tape_width" => null,
                    "tape_margin_sides" => 0.98,
                    "tape_margin_ends" => 0.68,
                    "tape_text_size_mod" => 0.33,
                ],
                [
                    "name" => "Avery L7162 1D Barcode",
                    "page_format" => "A4",
                    "page_orientation" => "P",
                    "column1_x" => 13.25,
                    "column2_x" => 301.25,
                    "row1_y" => 37.00,
                    "row2_y" => 133.00,
                    "label_width" => 280.80,
                    "label_height" => 96.00,
                    "barcode_size" => 6.00,
                    "barcode_margin" => 1.40,
                    "title_size" => 4.20,
                    "title_margin" => 1.20,
                    "field_size" => 4.20,
                    "field_margin" => 0.30,
                    "label_size" => 2.20,
                    "label_margin" => -0.50,
                    "tag_size" => 3.20,
                    "logo_max_width" => 25.00,
                    "logo_margin" => 2.20,
                    "measurement_unit" => 0.00,
                    "margin_top" => 1.00,
                    "margin_bottom" => 0.00,
                    "margin_left" => 1.00,
                    "margin_right" => 1.00,
                    "fields_supported" => 3,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 0,
                    "logo_option" => 1,
                    "title_option" => 1,
                    "tape_height" => 0.78,
                    "tape_width" => null,
                    "tape_margin_sides" => 0.00,
                    "tape_margin_ends" => 0.98,
                    "tape_text_size_mod" => 0.76,
                ],
                [
                    "name" => "Brother TZE 12mm",
                    "page_format" => "LETTER",
                    "page_orientation" => "P",
                    "column1_x" => 4.90,
                    "column2_x" => 1.83,
                    "row1_y" => 2.71,
                    "row2_y" => 3.97,
                    "label_width" => 2.48,
                    "label_height" => 3.33,
                    "barcode_size" => 1.00,
                    "barcode_margin" => 0.30,
                    "title_size" => null,
                    "title_margin" => null,
                    "field_size" => null,
                    "field_margin" => null,
                    "label_size" => null,
                    "label_margin" => null,
                    "tag_size" => null,
                    "logo_max_width" => 4.50,
                    "logo_margin" => 0.67,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.76,
                    "margin_bottom" => 0.12,
                    "margin_left" => 0.48,
                    "margin_right" => 0.97,
                    "fields_supported" => 1,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 0,
                    "logo_option" => 0,
                    "title_option" => 0,
                    "tape_height" => 12.00,
                    "tape_width" => null,
                    "tape_margin_sides" => 3.20,
                    "tape_margin_ends" => 3.20,
                    "tape_text_size_mod" => 1.00,
                ],
                [
                    "name" => "Brother TZE 18mm",
                    "page_format" => "LETTER",
                    "page_orientation" => "P",
                    "column1_x" => 5.70,
                    "column2_x" => 5.68,
                    "row1_y" => 2.85,
                    "row2_y" => 3.34,
                    "label_width" => 5.88,
                    "label_height" => 2.66,
                    "barcode_size" => 3.20,
                    "barcode_margin" => 0.30,
                    "title_size" => null,
                    "title_margin" => null,
                    "field_size" => null,
                    "field_margin" => null,
                    "label_size" => null,
                    "label_margin" => null,
                    "tag_size" => null,
                    "logo_max_width" => 4.94,
                    "logo_margin" => 0.66,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.99,
                    "margin_bottom" => 0.78,
                    "margin_left" => 0.04,
                    "margin_right" => 0.78,
                    "fields_supported" => 1,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 0,
                    "logo_option" => 0,
                    "title_option" => 0,
                    "tape_height" => 18.00,
                    "tape_width" => 50.00,
                    "tape_margin_sides" => 3.20,
                    "tape_margin_ends" => 3.20,
                    "tape_text_size_mod" => 1.00,
                ],
                [
                    "name" => "Brother TZE 24mm",
                    "page_format" => "LETTER",
                    "page_orientation" => "P",
                    "column1_x" => 0.45,
                    "column2_x" => 4.15,
                    "row1_y" => 0.23,
                    "row2_y" => 5.21,
                    "label_width" => 3.98,
                    "label_height" => 2.85,
                    "barcode_size" => null,
                    "barcode_margin" => 1.40,
                    "title_size" => 0.50,
                    "title_margin" => null,
                    "field_size" => 3.20,
                    "field_margin" => 0.15,
                    "label_size" => 2.00,
                    "label_margin" => -0.35,
                    "tag_size" => 2.80,
                    "logo_max_width" => 2.47,
                    "logo_margin" => 0.27,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.09,
                    "margin_bottom" => 0.27,
                    "margin_left" => 0.72,
                    "margin_right" => 0.23,
                    "fields_supported" => 3,
                    "tag_option" => 1,
                    "1d_barcode_option" => 0,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 24.00,
                    "tape_width" => 65.00,
                    "tape_margin_sides" => 3.20,
                    "tape_margin_ends" => 3.20,
                    "tape_text_size_mod" => null,
                ],
                [
                    "name" => "Dymo Label Writer 30252",
                    "page_format" => "",
                    "page_orientation" => "P",
                    "column1_x" => 3.60,
                    "column2_x" => 2.11,
                    "row1_y" => 5.35,
                    "row2_y" => 2.94,
                    "label_width" => 1.00,
                    "label_height" => 0.18,
                    "barcode_size" => null,
                    "barcode_margin" => 1.80,
                    "title_size" => 2.00,
                    "title_margin" => null,
                    "field_size" => 3.20,
                    "field_margin" => 0.15,
                    "label_size" => 2.00,
                    "label_margin" => -0.35,
                    "tag_size" => 2.80,
                    "logo_max_width" => 2.00,
                    "logo_margin" => 0.17,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.21,
                    "margin_bottom" => 0.35,
                    "margin_left" => 0.96,
                    "margin_right" => 0.55,
                    "fields_supported" => 3,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 1.15,
                    "tape_width" => 96.52,
                    "tape_margin_sides" => 0.10,
                    "tape_margin_ends" => 0.10,
                    "tape_text_size_mod" => null,
                ],
                [
                    "name" => "Dymo Label Writer 1933081",
                    "page_format" => "",
                    "page_orientation" => "P",
                    "column1_x" => 1.70,
                    "column2_x" => 1.34,
                    "row1_y" => 0.72,
                    "row2_y" => 5.01,
                    "label_width" => 3.88,
                    "label_height" => 2.15,
                    "barcode_size" => null,
                    "barcode_margin" => 1.80,
                    "title_size" => 2.80,
                    "title_margin" => 0.50,
                    "field_size" => 2.80,
                    "field_margin" => 0.15,
                    "label_size" => 2.80,
                    "label_margin" => -0.35,
                    "tag_size" => 2.80,
                    "logo_max_width" => 5.61,
                    "logo_margin" => 0.01,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.04,
                    "margin_bottom" => 0.16,
                    "margin_left" => 0.69,
                    "margin_right" => 0.57,
                    "fields_supported" => 5,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 25.00,
                    "tape_width" => 89.00,
                    "tape_margin_sides" => 0.10,
                    "tape_margin_ends" => 0.10,
                    "tape_text_size_mod" => null,
                ],
                [
                    "name" => "Dymo Label Writer 2112283",
                    "page_format" => "",
                    "page_orientation" => "P",
                    "column1_x" => 0.74,
                    "column2_x" => 0.59,
                    "row1_y" => 5.45,
                    "row2_y" => 0.76,
                    "label_width" => 5.73,
                    "label_height" => 2.26,
                    "barcode_size" => null,
                    "barcode_margin" => 1.80,
                    "title_size" => 2.80,
                    "title_margin" => 0.50,
                    "field_size" => 2.80,
                    "field_margin" => 0.15,
                    "label_size" => 2.80,
                    "label_margin" => -0.35,
                    "tag_size" => 2.80,
                    "logo_max_width" => 0.44,
                    "logo_margin" => 0.43,
                    "measurement_unit" => 0.00,
                    "margin_top" => 0.59,
                    "margin_bottom" => 0.50,
                    "margin_left" => 0.72,
                    "margin_right" => 0.58,
                    "fields_supported" => 5,
                    "tag_option" => 1,
                    "1d_barcode_option" => 1,
                    "2d_barcode_option" => 1,
                    "logo_option" => 0,
                    "title_option" => 1,
                    "tape_height" => 54.00,
                    "tape_width" => 25.00,
                    "tape_margin_sides" => 0.10,
                    "tape_margin_ends" => 0.10,
                    "tape_text_size_mod" => null,
                ]
            ];
        DB::table('label_templates')->insert($defaults);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('label_templates');
    }
}